"""Adiciona ondelete cascade para atendimentos

Revision ID: a14a0def7424
Revises: e9b0504e41ed
Create Date: 2025-11-06 12:21:52.997723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14a0def7424'
down_revision: Union[str, Sequence[str], None] = 'e9b0504e41ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('atendimentos_chamado_id_fkey'), 'atendimentos', type_='foreignkey')
    op.create_foreign_key(None, 'atendimentos', 'chamado', ['chamado_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atendimentos', type_='foreignkey')
    op.create_foreign_key(op.f('atendimentos_chamado_id_fkey'), 'atendimentos', 'chamado', ['chamado_id'], ['id'])
    # ### end Alembic commands ###
